### ISSUE TITLE
Throw exception when call setExpand(false) in RecyclerView.Adapter

### ISSUE THREAD

**Issue by akhbulatov** [yuzumone/ExpandableTextView#18]
Hi. This exception happened when I set `setExpand(false)` in `onBindViewHolder` of `RecyclerView.Adapter` on some text.
In this method of `ExpandableTextView` in first execute `if` block and then `else` one (`viewTreeObserver.addOnGlobalLayoutListener`) where exception is thrown (in `performEllipsize`)
```kotlin
private fun collapseText() {
        if (isFinishDraw) {
            performEllipsize()
        } else {
            viewTreeObserver.addOnGlobalLayoutListener(object : ViewTreeObserver.OnGlobalLayoutListener {
                override fun onGlobalLayout() {
                    viewTreeObserver.removeOnGlobalLayoutListener(this)
                    performEllipsize()
                }
            })
        }
    }
```

```
java.lang.ArrayIndexOutOfBoundsException: length=23; index=25
	at android.text.StaticLayout.getLineStart(StaticLayout.java:1231)
	at android.text.Layout.getLineVisibleEnd(Layout.java:1683)
	at android.text.Layout.getLineExtent(Layout.java:1412)
	at android.text.Layout.getLineMax(Layout.java:1389)
	at net.expandable.ExpandableTextView.performEllipsize(ExpandableTextView.kt:145)
	at net.expandable.ExpandableTextView.collapseText(ExpandableTextView.kt:131)
	at net.expandable.ExpandableTextView.setExpand(ExpandableTextView.kt:51)
	at com.example.MyAdapter$MyViewHolder$bind$$inlined$with$lambda$1.run(MyAdapter.kt:52)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by akhbulatov** [comment]
@yuzumone can you pay attention to this bug?

**Comment by yuzumone** [comment]
Thanks for the bug report. I'll fix it soon.
